# Generated by Django 5.1.7 on 2025-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
