# Generated by Django 4.2.3 on 2025-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItem', '0004_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
